### ISSUE TITLE
Can't install with TYPO3 10.4.10 and Composer

### ISSUE THREAD

**Issue by FurtFan86** [itplusx/flexible_pages#7]
Hello, when I want to install the extension I get the following error message in the console, even with the dev branch

Problem 1
    - Conclusion: don't install itplusx/flexible-pages v2.1.1
    - Conclusion: remove symfony/finder v5.1.8
    - Installation request for itplusx/flexible-pages ^2.1 -> satisfiable by itplusx/flexible-pages[v2.1.0, v2.1.1].
    - Conclusion: don't install symfony/finder v5.1.8
    - itplusx/flexible-pages v2.1.0 requires symfony/finder ^4.4 -> satisfiable by symfony/finder[v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - Can only install one of: symfony/finder[v4.4.0, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.1, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.10, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.11, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.12, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.13, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.14, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.15, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.16, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.17, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.18, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.2, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.3, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.4, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.5, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.6, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.7, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.8, v5.1.8].
    - Can only install one of: symfony/finder[v4.4.9, v5.1.8].
    - Installation request for symfony/finder (locked at v5.1.8) -> satisfiable by symfony/finder[v5.1.8].

**Comment by schloram** [comment]
Hi @FurtFan86 ,
thanks for the issue.

We just got back into office today. We will check and get back to you soon.

regards,
Ramón

**Comment by schloram** [comment]
Hi @FurtFan86 ,
this is fixed with v2.1.2. Please update the extension. Thanks for pointing it out. 👍 

regards,
Ramón
